In [ ]:
#from __future__ import print_function

J.R. Johansson (robert@riken.jp) http://dml.riken.jp/~rob/

The latest version of this IPython notebook lecture is available at http://github.com/jrjohansson/scientific-python-lectures.

The other notebooks in this lecture series are indexed at http://jrjohansson.github.com.
this notebook is based on the SciPy NumPy tutorial

Note that the traditional way to import `numpy` is to rename it `np`.  This saves on typing and makes your code a little more compact.

In [ ]:
import numpy as np

# Array Creation and Properties

Here we create an array using `arange` and then change its shape to be 3 rows and 5 columns.  Note the row-major ordering -- you'll see that the rows are together in the inner []

In [9]:
a = np.arange(15).reshape(3,5)

print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


A numpy array has a lot of meta-data associated with it describing its shape, datatype, etc.

In [11]:
print(a.ndim)
print(a.shape)

2
(3, 5)


In [10]:
print(a.size)

15


In [12]:
print(a.dtype)

int32


In [15]:
print(type(a))

<class 'numpy.ndarray'>


we can create an array from a list

In [18]:
b = np.array( [1.0, 2.0, 3.0, 4.0] )
print(b)
print(b.dtype)

[1. 2. 3. 4.]
float64


we can create a multi-dimensional array of a specified size initialized all to 0 easily.  There is also an analogous ones() and empty() array routine.  Note that here we explicitly set the datatype for the array. 

Unlike lists in python, all of the elements of a numpy array are of the same datatype

In [19]:
c = np.zeros( (10,7), dtype=np.float64)
print(c)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


`linspace` (and `logspace`) create arrays with evenly space (in log) numbers.  For `logspace`, you specify the start and ending powers (`base**start` to `base**stop`)

In [20]:
d = np.linspace(0, 1, 11, endpoint=True)
print(d)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [21]:
e = np.logspace(-1, 2, 15, endpoint=False, base=10)
print(e)

[ 0.1         0.15848932  0.25118864  0.39810717  0.63095734  1.
  1.58489319  2.51188643  3.98107171  6.30957344 10.         15.84893192
 25.11886432 39.81071706 63.09573445]


As always, as for help -- the numpy functions have very nice docstrings

In [22]:
help(np.logspace)

Help on function logspace in module numpy.core.function_base:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    Parameters
    ----------
    start : float
        ``base ** start`` is the starting value of the sequence.
    stop : float
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    base : float, optional
        The base of 

we can also initialize an array based on a function

In [23]:
f = np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
f

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [24]:
def myFun(x,y): 
    return 10*x+y

g = np.fromfunction(myFun, (5,4), dtype=int)
g

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

# Array Operations

most operations will work on an entire array at once

In [25]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [26]:
a.sum(axis=0)

array([12, 15, 18, 21])

In [27]:
a.sum()

66

In [28]:
print(a.min(), a.max())

0 11


### universal functions

In [29]:
b = a*np.pi/12.0
print(b)

[[0.         0.26179939 0.52359878 0.78539816]
 [1.04719755 1.30899694 1.57079633 1.83259571]
 [2.0943951  2.35619449 2.61799388 2.87979327]]


In [ ]:
c = np.cos(b)
print(c)

In [ ]:
d = b + c 

In [ ]:
print(d)

# Slicing

slicing works very similarly to how we saw with strings

In [30]:
a = np.fromfunction(myFun, (5,4),dtype=int)
print(a)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


Giving a single index (0-based) for each dimension just references a single value in the array

In [31]:
a[1,1]

11

Doing slices will access a range of elements.  Think of the start and stop in the slice as referencing the left-edge of the slots in the array.

In [32]:
a[0:2,0:2]

array([[ 0,  1],
       [10, 11]])

In [33]:
a[:,1]

array([ 1, 11, 21, 31, 41])

Sometimes we want a one-dimensional view into the array -- here we see the memory layout (row-major) more explicitly

In [34]:
a.flatten()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

we can also iterate -- this is done over the first axis

In [35]:
for row in a:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


or element by element

In [36]:
for e in a.flat:
    print(e)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [ ]:
help(a.flatten())

# Copying Arrays

simply using "=" does not make a copy, but much like with lists, you will just have multiple names pointing to the same ndarray object

In [37]:
a = np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [38]:
b = a
b is a

True

Since `b` and `a` are the same, changes to the shape of one are reflected in the other -- no copy is made.

In [39]:
b.shape = (2,5)
print(b)
a.shape

[[0 1 2 3 4]
 [5 6 7 8 9]]


(2, 5)

In [40]:
b is a

True

In [41]:
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


a shallow copy creates a new *view* into the array -- the data is the same, but the array properties can be different

In [42]:
a = np.arange(12)
c = a[:]
a.shape = (3,4)

print(a)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


since the underlying data is the same memory, changing an element of one is reflected in the other

In [43]:
c[1] = -1
print(a)

[[ 0 -1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [44]:
d = c[3:8]
print(d)

[3 4 5 6 7]


In [45]:
d[:] =0 

In [46]:
print(a)
print(c)
print(d)

[[ 0 -1  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]
[ 0 -1  2  0  0  0  0  0  8  9 10 11]
[0 0 0 0 0]


In [47]:
print(c is a)
print(c.base is a)
print(c.flags.owndata)
print(a.flags.owndata)

False
True
False
True


to make a copy of the data of the array that you can deal with independently of the original, you need a deep copy

In [48]:
d = a.copy()
d[:,:] = 0.0

print(a)
print(d)

[[ 0 -1  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# Boolean Indexing

In [49]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
a[a > 4] = 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [51]:
a[a == 0] = -1
a

array([[-1,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

if we have 2 tests, we need to use `logical_and()` or `logical_or()`

In [ ]:
a = np.arange(12).reshape(3,4)
a[np.logical_and(a > 3, a <= 9)] = 0.0
a

In [ ]:
a > 4